name: Jekflix | My Page | Perfeton
title: Jekflix | A blog theme for Jekyll | MY page 
description: Jekflix is a template for Jekyll inspired by Netflix and made by
  Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: synk@poczta.onet.pl
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
# My form https://formspree.io/f/xbjnjejl
formspree_form_id: xbjnjejl
