name: Perfeton - Not only the tech blog
title: "Perfeton | Blog: IT, Tech, Crypto and more"
description: "Perfeton is the blog about: IT, Tech, Crypto and more" 
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
# email: e-mail
# See: https://disqus.com/
#disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
# My form https://formspree.io/f/myyrzwya
formspree_form_id: myyrzwya
